
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod

bases:
  - ../../base

resources:
  - namespace.yaml

images:
  - name: quay.io/pittar/petclinic
    newName: quay.io/pittar/petclinic
    newTag: metrics
