apiVersion: v1                    
kind: Namespace
metadata:
  name: application-petclinic-dev                             
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: channel-petclinic-dev                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: petclinic-dev
  namespace: application-petclinic-dev
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - petclinic-dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: petclinic-dev
  namespace: channel-petclinic-dev
spec:
  type: Git
  pathname: https://github.com/pittar-demos/intro-to-acm-and-acs
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 02-gitops-apps/petclinic/overlays/dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: petclinic-dev
  name: petclinic-dev-subscription
  namespace: application-petclinic-dev
spec:
  channel: channel-petclinic-dev/petclinic-dev
  placement:
    placementRef:
      kind: PlacementRule
      name: petclinic-dev-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: petclinic-dev
  name: petclinic-dev-placement
  namespace: application-petclinic-dev
spec:
  clusterSelector:
    matchLabels:
      'petclinic-dev': 'true'