apiVersion: v1                    
kind: Namespace
metadata:
  name: petclinic-test                             
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: channel-petclinic-test                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: petclinic-test
  namespace: petclinic-test
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - petclinic-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: petclinic-test
  namespace: channel-petclinic-test
spec:
  pathname: https://github.com/pittar-demos/intro-to-acm-and-acs
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 02-gitops-apps/petclinic/overlays/test
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: petclinic-test
  name: petclinic-test-subscription
  namespace: petclinic-test
spec:
  channel: channel-petclinic-test/petclinic-test
  placement:
    placementRef:
      kind: PlacementRule
      name: petclinic-test-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: petclinic-test
  name: petclinic-test-placement
  namespace: petclinic-test
spec:
  clusterSelector:
    matchLabels:
      'petclinic-test': 'true'